server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FurkanMelek/config-repo.git
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          clone-on-start: true
encrypt:
  key: mySecretKey123456
   # The Cipher key, for sensitive infos like DB conn, JWT key...
   # I Prefer that way to more security. İf you have not my key, so you will not get my DB connections info
