server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FurkanMelek/config-repo.git
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
          clone-on-start: true
encrypt:
  key: mySecretKey123456 # Bu key cipher için kullanılıyor